<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'a2lix_translation_form.default.type.translationsForms' shared service.

return $this->services['a2lix_translation_form.default.type.translationsForms'] = new \A2lix\TranslationFormBundle\Form\Type\TranslationsFormsType(${($_ = isset($this->services['a2lix_translation_form.default.service.translation']) ? $this->services['a2lix_translation_form.default.service.translation'] : $this->load(__DIR__.'/getA2lixTranslationForm_Default_Service_TranslationService.php')) && false ?: '_'}, ${($_ = isset($this->services['a2lix_translation_form.default.listener.translationsForms']) ? $this->services['a2lix_translation_form.default.listener.translationsForms'] : $this->services['a2lix_translation_form.default.listener.translationsForms'] = new \A2lix\TranslationFormBundle\Form\EventListener\TranslationsFormsListener()) && false ?: '_'}, ${($_ = isset($this->services['a2lix_translation_form.default.service.parameter_locale_provider']) ? $this->services['a2lix_translation_form.default.service.parameter_locale_provider'] : $this->services['a2lix_translation_form.default.service.parameter_locale_provider'] = new \A2lix\TranslationFormBundle\Locale\DefaultProvider($this->parameters['cocorico.locales'], 'fr', $this->parameters['cocorico.locales'])) && false ?: '_'});
