<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico.booking_payin_refund.manager' shared service.

return $this->services['cocorico.booking_payin_refund.manager'] = new \Cocorico\CoreBundle\Model\Manager\BookingPayinRefundManager(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, $this->parameters['cocorico.booking.cancelation_policy'], ${($_ = isset($this->services['cocorico.mailer.twig_swift']) ? $this->services['cocorico.mailer.twig_swift'] : $this->load(__DIR__.'/getCocorico_Mailer_TwigSwiftService.php')) && false ?: '_'}, 10, $this->parameters['kernel.bundles']);
