<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico.extra_bundle.routing_loader' shared service.

return $this->services['cocorico.extra_bundle.routing_loader'] = new \Cocorico\CoreBundle\Routing\ExtraBundleLoader($this->parameters['kernel.bundles'], 'dev');
