<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico.form.booking.status_filter' shared service.

return $this->services['cocorico.form.booking.status_filter'] = new \Cocorico\CoreBundle\Form\Type\Dashboard\BookingStatusFilterType();
