<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico.namer.image_namer' shared service.

return $this->services['cocorico.namer.image_namer'] = new \Cocorico\CoreBundle\Namer\ImageNamer();
