<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico.star_rating.form.type' shared service.

return $this->services['cocorico.star_rating.form.type'] = new \Cocorico\ReviewBundle\Form\Type\StarRatingType();
