<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico.breadcrumbs_manager' shared service.

return $this->services['cocorico.breadcrumbs_manager'] = new \Cocorico\BreadcrumbBundle\Services\BreadcrumbsManager(${($_ = isset($this->services['white_october_breadcrumbs']) ? $this->services['white_october_breadcrumbs'] : $this->load(__DIR__.'/getWhiteOctoberBreadcrumbsService.php')) && false ?: '_'}, ${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'}, ${($_ = isset($this->services['cocorico.breadcrumbs_loader']) ? $this->services['cocorico.breadcrumbs_loader'] : $this->load(__DIR__.'/getCocorico_BreadcrumbsLoaderService.php')) && false ?: '_'}, ${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'}, ${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'});
