<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico.booking_bank_wire.manager' shared service.

return $this->services['cocorico.booking_bank_wire.manager'] = new \Cocorico\CoreBundle\Model\Manager\BookingBankWireManager(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, false, ${($_ = isset($this->services['cocorico.mailer.twig_swift']) ? $this->services['cocorico.mailer.twig_swift'] : $this->load(__DIR__.'/getCocorico_Mailer_TwigSwiftService.php')) && false ?: '_'}, 10, ${($_ = isset($this->services['debug.event_dispatcher']) ? $this->services['debug.event_dispatcher'] : $this->getDebug_EventDispatcherService()) && false ?: '_'}, $this->parameters['kernel.bundles']);
