<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico.form.type.country_filtered' shared service.

return $this->services['cocorico.form.type.country_filtered'] = new \Cocorico\CoreBundle\Form\Type\CountryFilteredType(array(), $this->parameters['cocorico.listing_favorite_countries']);
