<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'cocorico_user.form.handler.registration' shared service.

return $this->services['cocorico_user.form.handler.registration'] = new \Cocorico\UserBundle\Form\Handler\RegistrationFormHandler(${($_ = isset($this->services['request_stack']) ? $this->services['request_stack'] : $this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()) && false ?: '_'}, ${($_ = isset($this->services['cocorico_user.user_manager']) ? $this->services['cocorico_user.user_manager'] : $this->load(__DIR__.'/getCocoricoUser_UserManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['cocorico_user.mailer.twig_swift']) ? $this->services['cocorico_user.mailer.twig_swift'] : $this->load(__DIR__.'/getCocoricoUser_Mailer_TwigSwiftService.php')) && false ?: '_'}, ${($_ = isset($this->services['fos_user.util.token_generator']) ? $this->services['fos_user.util.token_generator'] : $this->services['fos_user.util.token_generator'] = new \FOS\UserBundle\Util\TokenGenerator()) && false ?: '_'}, ${($_ = isset($this->services['cocorico_user.login_manager']) ? $this->services['cocorico_user.login_manager'] : $this->load(__DIR__.'/getCocoricoUser_LoginManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['debug.event_dispatcher']) ? $this->services['debug.event_dispatcher'] : $this->getDebug_EventDispatcherService()) && false ?: '_'});
