<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico.form.type.listing_search_result' shared service.

return $this->services['cocorico.form.type.listing_search_result'] = new \Cocorico\CoreBundle\Form\Type\Frontend\ListingSearchResultType(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, ${($_ = isset($this->services['request_stack']) ? $this->services['request_stack'] : $this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()) && false ?: '_'}, ${($_ = isset($this->services['debug.event_dispatcher']) ? $this->services['debug.event_dispatcher'] : $this->getDebug_EventDispatcherService()) && false ?: '_'}, array('parameters' => array('cocorico_time_unit' => 1440, 'cocorico_time_unit_flexibility' => 0, 'cocorico_days_display_mode' => 'range', 'cocorico_times_display_mode' => 'duration', 'cocorico_booking_allow_single_day' => true, 'cocorico_booking_end_day_included' => true, 'cocorico_booking_min_start_delay' => 0)));
