<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico_user.authentication_subscriber' shared service.

return $this->services['cocorico_user.authentication_subscriber'] = new \Cocorico\UserBundle\Event\UserAuthenticationSubscriber(${($_ = isset($this->services['session']) ? $this->services['session'] : $this->getSessionService()) && false ?: '_'}, 'Europe/Paris');
