<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico.form.type.review_new' shared service.

return $this->services['cocorico.form.type.review_new'] = new \Cocorico\ReviewBundle\Form\Type\Dashboard\ReviewType();
