<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_message.new_thread_form.factory' shared service.

return $this->services['fos_message.new_thread_form.factory'] = new \FOS\MessageBundle\FormFactory\NewThreadMessageFormFactory(${($_ = isset($this->services['form.factory']) ? $this->services['form.factory'] : $this->load(__DIR__.'/getForm_FactoryService.php')) && false ?: '_'}, 'Cocorico\\MessageBundle\\Form\\Type\\Frontend\\NewThreadMessageFormType', 'message', 'Cocorico\\MessageBundle\\FormModel\\NewThreadMessage');
