<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'lexik_currency.adapter_factory' shared service.

return $this->services['lexik_currency.adapter_factory'] = new \Lexik\Bundle\CurrencyBundle\Adapter\AdapterFactory(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'}, 'EUR', $this->parameters['lexik_currency.currencies.managed'], 'Lexik\\Bundle\\CurrencyBundle\\Entity\\Currency');
