<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'lexik_currency.adapter_collector' shared service.

$this->services['lexik_currency.adapter_collector'] = $instance = new \Lexik\Bundle\CurrencyBundle\Adapter\AdapterCollector();

$instance->add(${($_ = isset($this->services['lexik_currency.doctrine_adapter']) ? $this->services['lexik_currency.doctrine_adapter'] : $this->load(__DIR__.'/getLexikCurrency_DoctrineAdapterService.php')) && false ?: '_'});
$instance->add(${($_ = isset($this->services['lexik_currency.ecb_adapter']) ? $this->services['lexik_currency.ecb_adapter'] : $this->load(__DIR__.'/getLexikCurrency_EcbAdapterService.php')) && false ?: '_'});
$instance->add(${($_ = isset($this->services['lexik_currency.oer_adapter']) ? $this->services['lexik_currency.oer_adapter'] : $this->load(__DIR__.'/getLexikCurrency_OerAdapterService.php')) && false ?: '_'});
$instance->add(${($_ = isset($this->services['lexik_currency.yahoo_adapter']) ? $this->services['lexik_currency.yahoo_adapter'] : $this->load(__DIR__.'/getLexikCurrency_YahooAdapterService.php')) && false ?: '_'});

return $instance;
