<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'oneup_uploader.storage.user_images' shared service.

return $this->services['oneup_uploader.storage.user_images'] = new \Oneup\UploaderBundle\Uploader\Storage\FilesystemStorage('/cocorico/app/../web/uploads/users/images');
