<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.access.review_voter' shared service.

return $this->services['security.access.review_voter'] = new \Cocorico\ReviewBundle\Security\Voter\ReviewVoter();
