<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico.booking_payin_refund.subscriber' shared service.

return $this->services['cocorico.booking_payin_refund.subscriber'] = new \Cocorico\CoreBundle\Event\BookingPayinRefundSubscriber(${($_ = isset($this->services['cocorico.booking_payin_refund.manager']) ? $this->services['cocorico.booking_payin_refund.manager'] : $this->load(__DIR__.'/getCocorico_BookingPayinRefund_ManagerService.php')) && false ?: '_'});
