<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico_user.login_manager' shared service.

return $this->services['cocorico_user.login_manager'] = new \Cocorico\UserBundle\Security\LoginManager(${($_ = isset($this->services['cocorico_user.user_manager']) ? $this->services['cocorico_user.user_manager'] : $this->load(__DIR__.'/getCocoricoUser_UserManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['fos_user.security.login_manager']) ? $this->services['fos_user.security.login_manager'] : $this->load(__DIR__.'/getFosUser_Security_LoginManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['security.encoder_factory']) ? $this->services['security.encoder_factory'] : $this->getSecurity_EncoderFactoryService()) && false ?: '_'}, 'main');
