<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico.form.type.listing_listing_characteristic' shared service.

return $this->services['cocorico.form.type.listing_listing_characteristic'] = new \Cocorico\CoreBundle\Form\Type\ListingListingCharacteristicType(${($_ = isset($this->services['request_stack']) ? $this->services['request_stack'] : $this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()) && false ?: '_'});
