<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico_user.form.type.register' shared service.

return $this->services['cocorico_user.form.type.register'] = new \Cocorico\UserBundle\Form\Type\RegistrationFormType();
