<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico_geo.form.type.geocoding' shared service.

return $this->services['cocorico_geo.form.type.geocoding'] = new \Cocorico\GeoBundle\Form\Type\GeocodingToCoordinateType(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, $this->parameters['cocorico.locales'], ${($_ = isset($this->services['request_stack']) ? $this->services['request_stack'] : $this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()) && false ?: '_'}, 'AIzaSyASijJ05pLq3ha4mKrriQsJcTQUHQgFMd0');
