<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico.image_type_extension' shared service.

return $this->services['cocorico.image_type_extension'] = new \Cocorico\CoreBundle\Form\Extension\ImageTypeExtension();
