<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico_user.listing_image_upload_validation_listener' shared service.

return $this->services['cocorico_user.listing_image_upload_validation_listener'] = new \Cocorico\UserBundle\Listener\UserImageUploadValidationListener(12);
