<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico.form.type.price_range' shared service.

return $this->services['cocorico.form.type.price_range'] = new \Cocorico\CoreBundle\Form\Type\PriceRangeType(${($_ = isset($this->services['session']) ? $this->services['session'] : $this->getSessionService()) && false ?: '_'}, 'EUR');
