<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico_user.oauth.user.provider.entity' shared service.

return $this->services['cocorico_user.oauth.user.provider.entity'] = new \Cocorico\UserBundle\Security\OAuthUserProvider(${($_ = isset($this->services['cocorico_user.user_manager']) ? $this->services['cocorico_user.user_manager'] : $this->load(__DIR__.'/getCocoricoUser_UserManagerService.php')) && false ?: '_'});
