<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico.form.type.booking_new' shared service.

return $this->services['cocorico.form.type.booking_new'] = new \Cocorico\CoreBundle\Form\Type\Frontend\BookingNewType(${($_ = isset($this->services['cocorico.booking.manager']) ? $this->services['cocorico.booking.manager'] : $this->load(__DIR__.'/getCocorico_Booking_ManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['debug.event_dispatcher']) ? $this->services['debug.event_dispatcher'] : $this->getDebug_EventDispatcherService()) && false ?: '_'}, array('parameters' => array('cocorico_booking_allow_single_day' => true, 'cocorico_booking_end_day_included' => true, 'cocorico_booking_min_start_delay' => 0, 'cocorico_booking_min_start_time_delay' => 720, 'cocorico_currency' => 'EUR', 'cocorico_user_address_delivery' => true)));
