<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico.form.handler.booking.offerer.dashboard' shared service.

$this->services['cocorico.form.handler.booking.offerer.dashboard'] = $instance = new \Cocorico\CoreBundle\Form\Handler\Dashboard\BookingOffererFormHandler();

$instance->setRequest(${($_ = isset($this->services['request_stack']) ? $this->services['request_stack'] : $this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()) && false ?: '_'});
$instance->setBookingManager(${($_ = isset($this->services['cocorico.booking.manager']) ? $this->services['cocorico.booking.manager'] : $this->load(__DIR__.'/getCocorico_Booking_ManagerService.php')) && false ?: '_'});
$instance->setThreadManager(${($_ = isset($this->services['cocorico_message.thread_manager']) ? $this->services['cocorico_message.thread_manager'] : $this->load(__DIR__.'/getCocoricoMessage_ThreadManagerService.php')) && false ?: '_'});

return $instance;
