<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doctrine.fixtures_load_command' shared service.

$a = new \Doctrine\Bundle\FixturesBundle\Loader\SymfonyFixturesLoader($this);
$a->addFixtures(array(0 => new \Cocorico\CoreBundle\DataFixtures\ORM\CurrencyFixtures(), 1 => new \Cocorico\CoreBundle\DataFixtures\ORM\ListingCategoryFixtures(), 2 => new \Cocorico\CoreBundle\DataFixtures\ORM\ListingCharacteristicFixtures(), 3 => new \Cocorico\CoreBundle\DataFixtures\ORM\ListingCharacteristicGroupFixtures(), 4 => new \Cocorico\CoreBundle\DataFixtures\ORM\ListingCharacteristicTypeFixtures(), 5 => new \Cocorico\CoreBundle\DataFixtures\ORM\ListingCharacteristicValueFixtures(), 6 => new \Cocorico\CoreBundle\DataFixtures\ORM\ListingFixtures(), 7 => new \Cocorico\CoreBundle\DataFixtures\ORM\PageFixtures(), 8 => new \Cocorico\CoreBundle\DataFixtures\ORM\UserFixtures()));

$this->services['doctrine.fixtures_load_command'] = $instance = new \Doctrine\Bundle\FixturesBundle\Command\LoadDataFixturesDoctrineCommand($a);

$instance->setName('doctrine:fixtures:load');

return $instance;
