<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_user.username_form_type' shared service.

return $this->services['fos_user.username_form_type'] = new \FOS\UserBundle\Form\Type\UsernameFormType(${($_ = isset($this->services['fos_user.user_to_username_transformer']) ? $this->services['fos_user.user_to_username_transformer'] : $this->load(__DIR__.'/getFosUser_UserToUsernameTransformerService.php')) && false ?: '_'});
