<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_message.reply_form.handler' shared service.

return $this->services['fos_message.reply_form.handler'] = new \FOS\MessageBundle\FormHandler\ReplyMessageFormHandler(${($_ = isset($this->services['request_stack']) ? $this->services['request_stack'] : $this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()) && false ?: '_'}, ${($_ = isset($this->services['fos_message.composer']) ? $this->services['fos_message.composer'] : $this->load(__DIR__.'/getFosMessage_ComposerService.php')) && false ?: '_'}, ${($_ = isset($this->services['fos_message.sender']) ? $this->services['fos_message.sender'] : $this->load(__DIR__.'/getFosMessage_SenderService.php')) && false ?: '_'}, ${($_ = isset($this->services['fos_message.participant_provider']) ? $this->services['fos_message.participant_provider'] : $this->getFosMessage_ParticipantProviderService()) && false ?: '_'});
