<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'lexik_currency.converter' shared service.

return $this->services['lexik_currency.converter'] = new \Lexik\Bundle\CurrencyBundle\Currency\Converter(${($_ = isset($this->services['lexik_currency.doctrine_adapter']) ? $this->services['lexik_currency.doctrine_adapter'] : $this->load(__DIR__.'/getLexikCurrency_DoctrineAdapterService.php')) && false ?: '_'}, 0, 'up');
