<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.user.form.type.security_roles' shared service.

return $this->services['sonata.user.form.type.security_roles'] = new \Sonata\UserBundle\Form\Type\SecurityRolesType(${($_ = isset($this->services['sonata.user.editable_role_builder']) ? $this->services['sonata.user.editable_role_builder'] : $this->load(__DIR__.'/getSonata_User_EditableRoleBuilderService.php')) && false ?: '_'});
