<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.admin.audit.orm.reader' shared service.

return $this->services['sonata.admin.audit.orm.reader'] = new \Sonata\DoctrineORMAdminBundle\Model\AuditReader(${($_ = isset($this->services['simplethings_entityaudit.reader']) ? $this->services['simplethings_entityaudit.reader'] : $this->load(__DIR__.'/getSimplethingsEntityaudit_ReaderService.php')) && false ?: '_'});
