<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJn9kpxs\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJn9kpxs/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJn9kpxs.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJn9kpxs\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerJn9kpxs\appDevDebugProjectContainer();
