<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'a2lix_translation_form.default.listener.translations' shared service.

return $this->services['a2lix_translation_form.default.listener.translations'] = new \A2lix\TranslationFormBundle\Form\EventListener\TranslationsListener(${($_ = isset($this->services['a2lix_translation_form.default.service.translation']) ? $this->services['a2lix_translation_form.default.service.translation'] : $this->load(__DIR__.'/getA2lixTranslationForm_Default_Service_TranslationService.php')) && false ?: '_'});
