<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'a2lix_translation_form.default.type.translations' shared service.

return $this->services['a2lix_translation_form.default.type.translations'] = new \A2lix\TranslationFormBundle\Form\Type\TranslationsType(${($_ = isset($this->services['a2lix_translation_form.default.listener.translations']) ? $this->services['a2lix_translation_form.default.listener.translations'] : $this->load(__DIR__.'/getA2lixTranslationForm_Default_Listener_TranslationsService.php')) && false ?: '_'}, ${($_ = isset($this->services['a2lix_translation_form.default.service.parameter_locale_provider']) ? $this->services['a2lix_translation_form.default.service.parameter_locale_provider'] : $this->services['a2lix_translation_form.default.service.parameter_locale_provider'] = new \A2lix\TranslationFormBundle\Locale\DefaultProvider($this->parameters['cocorico.locales'], 'fr', $this->parameters['cocorico.locales'])) && false ?: '_'});
