<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico_message.mailer.twig_swift' shared service.

return $this->services['cocorico_message.mailer.twig_swift'] = new \Cocorico\MessageBundle\Mailer\TwigSwiftMailer(${($_ = isset($this->services['swiftmailer.mailer.default']) ? $this->services['swiftmailer.mailer.default'] : $this->load(__DIR__.'/getSwiftmailer_Mailer_DefaultService.php')) && false ?: '_'}, ${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'}, ${($_ = isset($this->services['twig']) ? $this->services['twig'] : $this->getTwigService()) && false ?: '_'}, ${($_ = isset($this->services['request_stack']) ? $this->services['request_stack'] : $this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()) && false ?: '_'}, array('parameters' => array('cocorico_locales' => $this->parameters['cocorico.locales'], 'cocorico_locale' => 'fr', 'cocorico_from_email' => 'no-reply@cocorico.io')), array('templates' => array('new_thread_message_user' => 'CocoricoMessageBundle:Mails:new_thread_message_user.txt.twig')));
