<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico.booking_validator' shared service.

return $this->services['cocorico.booking_validator'] = new \Cocorico\CoreBundle\Validator\Constraints\BookingValidator(${($_ = isset($this->services['cocorico.booking.manager']) ? $this->services['cocorico.booking.manager'] : $this->load(__DIR__.'/getCocorico_Booking_ManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['session']) ? $this->services['session'] : $this->getSessionService()) && false ?: '_'}, 0, 720, 'EUR');
