<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico_message.booking.subscriber' shared service.

return $this->services['cocorico_message.booking.subscriber'] = new \Cocorico\MessageBundle\Event\BookingSubscriber(${($_ = isset($this->services['cocorico_message.thread_manager']) ? $this->services['cocorico_message.thread_manager'] : $this->load(__DIR__.'/getCocoricoMessage_ThreadManagerService.php')) && false ?: '_'});
