<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico.listing_availability_time.manager' shared service.

return $this->services['cocorico.listing_availability_time.manager'] = new \Cocorico\CoreBundle\Model\Manager\ListingAvailabilityTimeManager(${($_ = isset($this->services['doctrine_mongodb.odm.default_document_manager']) ? $this->services['doctrine_mongodb.odm.default_document_manager'] : $this->getDoctrineMongodb_Odm_DefaultDocumentManagerService()) && false ?: '_'}, 1440, 1);
