<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico.form.type.listing_edit_availabilities_prices' shared service.

return $this->services['cocorico.form.type.listing_edit_availabilities_prices'] = new \Cocorico\CoreBundle\Form\Type\Dashboard\ListingEditAvailabilitiesPricesType(1440, 360);
