<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico_time.times_range_overlap_validator' shared service.

return $this->services['cocorico_time.times_range_overlap_validator'] = new \Cocorico\TimeBundle\Validator\Constraints\TimeRangesOverlapValidator();
