<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico_time.form.type.date_hidden' shared service.

return $this->services['cocorico_time.form.type.date_hidden'] = new \Cocorico\TimeBundle\Form\Type\DateHiddenType();
