<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico_contact.form.type.contact_new' shared service.

return $this->services['cocorico_contact.form.type.contact_new'] = new \Cocorico\ContactBundle\Form\Type\Frontend\ContactNewType();
