<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico_time.form.type.time_range' shared service.

return $this->services['cocorico_time.form.type.time_range'] = new \Cocorico\TimeBundle\Form\Type\TimeRangeType(${($_ = isset($this->services['session']) ? $this->services['session'] : $this->getSessionService()) && false ?: '_'}, 1440, 8, $this->parameters['cocorico.time_hours_available']);
