<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico_contact.mailer.twig_swift' shared service.

return $this->services['cocorico_contact.mailer.twig_swift'] = new \Cocorico\ContactBundle\Mailer\TwigSwiftMailer(${($_ = isset($this->services['swiftmailer.mailer.default']) ? $this->services['swiftmailer.mailer.default'] : $this->load(__DIR__.'/getSwiftmailer_Mailer_DefaultService.php')) && false ?: '_'}, ${($_ = isset($this->services['twig']) ? $this->services['twig'] : $this->getTwigService()) && false ?: '_'}, array('parameters' => array('cocorico_locale' => 'fr', 'cocorico_contact_from_email' => 'no-reply@cocorico.io', 'cocorico_contact_contact_email' => 'contact@costocking.com')), array('templates' => array('contact_message' => 'CocoricoContactBundle:Mails:contact_message.txt.twig')));
