<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico.form.type.booking_edit' shared service.

return $this->services['cocorico.form.type.booking_edit'] = new \Cocorico\CoreBundle\Form\Type\Dashboard\BookingEditType();
