<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico_user.security.access.user_image_voter' shared service.

return $this->services['cocorico_user.security.access.user_image_voter'] = new \Cocorico\UserBundle\Security\Voter\UserImageVoter();
