<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico_time.form.type.weekdays' shared service.

return $this->services['cocorico_time.form.type.weekdays'] = new \Cocorico\TimeBundle\Form\Type\WeekDaysType();
