<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'cocorico.listing_search.manager' shared service.

return $this->services['cocorico.listing_search.manager'] = new \Cocorico\CoreBundle\Model\Manager\ListingSearchManager(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, ${($_ = isset($this->services['doctrine_mongodb.odm.default_document_manager']) ? $this->services['doctrine_mongodb.odm.default_document_manager'] : $this->getDoctrineMongodb_Odm_DefaultDocumentManagerService()) && false ?: '_'}, ${($_ = isset($this->services['debug.event_dispatcher']) ? $this->services['debug.event_dispatcher'] : $this->getDebug_EventDispatcherService()) && false ?: '_'}, array('parameters' => array('cocorico_booking_end_day_included' => true, 'cocorico_time_unit' => 1440, 'cocorico_listing_search_max_per_page' => 10, 'cocorico_listing_availability_status' => 1)));
