<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico.translator.breadcrumbs_extractor' shared service.

return $this->services['cocorico.translator.breadcrumbs_extractor'] = new \Cocorico\BreadcrumbBundle\Translator\BreadcrumbsExtractor(${($_ = isset($this->services['cocorico.breadcrumbs_loader']) ? $this->services['cocorico.breadcrumbs_loader'] : $this->load(__DIR__.'/getCocorico_BreadcrumbsLoaderService.php')) && false ?: '_'}, $this->parameters['white_october_breadcrumbs.options']);
