<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico.form.type.listing_edit_description' shared service.

return $this->services['cocorico.form.type.listing_edit_description'] = new \Cocorico\CoreBundle\Form\Type\Dashboard\ListingEditDescriptionType(${($_ = isset($this->services['security.token_storage']) ? $this->services['security.token_storage'] : $this->services['security.token_storage'] = new \Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage()) && false ?: '_'}, ${($_ = isset($this->services['request_stack']) ? $this->services['request_stack'] : $this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()) && false ?: '_'}, $this->parameters['cocorico.locales'], ${($_ = isset($this->services['cocorico.listing.manager']) ? $this->services['cocorico.listing.manager'] : $this->load(__DIR__.'/getCocorico_Listing_ManagerService.php')) && false ?: '_'}, 1440);
