<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico.booking.subscriber' shared service.

return $this->services['cocorico.booking.subscriber'] = new \Cocorico\CoreBundle\Event\BookingSubscriber(${($_ = isset($this->services['cocorico.booking.manager']) ? $this->services['cocorico.booking.manager'] : $this->load(__DIR__.'/getCocorico_Booking_ManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['debug.event_dispatcher']) ? $this->services['debug.event_dispatcher'] : $this->getDebug_EventDispatcherService()) && false ?: '_'});
