<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'jms_i18n_routing.loader' shared service.

return $this->services['jms_i18n_routing.loader'] = new \JMS\I18nRoutingBundle\Router\I18nLoader(${($_ = isset($this->services['jms_i18n_routing.route_exclusion_strategy']) ? $this->services['jms_i18n_routing.route_exclusion_strategy'] : $this->services['jms_i18n_routing.route_exclusion_strategy'] = new \JMS\I18nRoutingBundle\Router\DefaultRouteExclusionStrategy()) && false ?: '_'}, new \JMS\I18nRoutingBundle\Router\DefaultPatternGenerationStrategy('prefix', ${($_ = isset($this->services['translator']) ? $this->services['translator'] : $this->getTranslatorService()) && false ?: '_'}, $this->parameters['jms_i18n_routing.locales'], $this->targetDirs[0], 'routes', 'fr'));
