<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sonata.admin.audit.manager' shared service.

$this->services['sonata.admin.audit.manager'] = $instance = new \Sonata\AdminBundle\Model\AuditManager($this);

$instance->setReader('sonata.admin.audit.orm.reader', $this->parameters['simplethings.entityaudit.audited_entities']);

return $instance;
