<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sonata.admin.translator.extractor.jms_translator_bundle' shared service.

$this->services['sonata.admin.translator.extractor.jms_translator_bundle'] = $instance = new \Sonata\AdminBundle\Translator\Extractor\JMSTranslatorBundle\AdminExtractor(${($_ = isset($this->services['sonata.admin.pool']) ? $this->services['sonata.admin.pool'] : $this->getSonata_Admin_PoolService()) && false ?: '_'}, ${($_ = isset($this->services['logger']) ? $this->services['logger'] : $this->getLoggerService()) && false ?: '_'});

$instance->setBreadcrumbsBuilder(${($_ = isset($this->services['sonata.admin.breadcrumbs_builder']) ? $this->services['sonata.admin.breadcrumbs_builder'] : $this->load(__DIR__.'/getSonata_Admin_BreadcrumbsBuilderService.php')) && false ?: '_'});

return $instance;
