<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.user.manager.user' shared service.

return $this->services['sonata.user.manager.user'] = new \Sonata\UserBundle\Entity\UserManagerProxy('Cocorico\\UserBundle\\Entity\\User', ${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'}, ${($_ = isset($this->services['sonata.user.user_manager']) ? $this->services['sonata.user.user_manager'] : $this->load(__DIR__.'/getSonata_User_UserManagerService.php')) && false ?: '_'});
