<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'cocorico_message.new_thread.form.type' shared service.

return $this->services['cocorico_message.new_thread.form.type'] = new \Cocorico\MessageBundle\Form\Type\Frontend\NewThreadMessageFormType('Cocorico\\MessageBundle\\Entity\\Thread');
