<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico_user.profile_about_me.form.type' shared service.

return $this->services['cocorico_user.profile_about_me.form.type'] = new \Cocorico\UserBundle\Form\Type\ProfileAboutMeFormType('Cocorico\\UserBundle\\Entity\\User', ${($_ = isset($this->services['request_stack']) ? $this->services['request_stack'] : $this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()) && false ?: '_'}, $this->parameters['cocorico.locales']);
