<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico.translator.entity.extractor' shared service.

return $this->services['cocorico.translator.entity.extractor'] = new \Cocorico\CoreBundle\Translator\EntityExtractor();
