<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico_message.message.subscriber' shared service.

return $this->services['cocorico_message.message.subscriber'] = new \Cocorico\MessageBundle\Event\MessageSubscriber(${($_ = isset($this->services['cocorico_message.mailer.twig_swift']) ? $this->services['cocorico_message.mailer.twig_swift'] : $this->load(__DIR__.'/getCocoricoMessage_Mailer_TwigSwiftService.php')) && false ?: '_'});
