<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico.listing_discount_validator' shared service.

return $this->services['cocorico.listing_discount_validator'] = new \Cocorico\CoreBundle\Validator\Constraints\ListingDiscountValidator(1, 90);
