<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico.breadcrumbs_yaml_locator' shared service.

return $this->services['cocorico.breadcrumbs_yaml_locator'] = new \Symfony\Component\Config\FileLocator('/cocorico/app/../src/Cocorico/BreadcrumbBundle/Resources/content/');
