<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico.translator.admin.extractor' shared service.

return $this->services['cocorico.translator.admin.extractor'] = new \Cocorico\CoreBundle\Translator\AdminExtractor();
