<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico.form.type.listing_edit_availabilities' shared service.

return $this->services['cocorico.form.type.listing_edit_availabilities'] = new \Cocorico\CoreBundle\Form\Type\Dashboard\ListingEditAvailabilitiesType(1440, 360);
