<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_user.resetting.form.type' shared service.

return $this->services['fos_user.resetting.form.type'] = new \Cocorico\UserBundle\Form\Type\ResettingFormType('Cocorico\\UserBundle\\Entity\\User');
