<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Doctrine\Bundle\MongoDBBundle\Command\GenerateDocumentsDoctrineODMCommand' shared service.

return $this->services['Doctrine\Bundle\MongoDBBundle\Command\GenerateDocumentsDoctrineODMCommand'] = new \Doctrine\Bundle\MongoDBBundle\Command\GenerateDocumentsDoctrineODMCommand();
