<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Geocoder\Dumper\Kml' shared service.

return $this->services['Geocoder\Dumper\Kml'] = new \Geocoder\Dumper\Kml();
