<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Geocoder\ProviderAggregator' shared service.

$this->services['Geocoder\ProviderAggregator'] = $instance = new \Geocoder\ProviderAggregator();

$instance->registerProviders(array(0 => ${($_ = isset($this->services['bazinga_geocoder.provider.google_maps']) ? $this->services['bazinga_geocoder.provider.google_maps'] : $this->load(__DIR__.'/getBazingaGeocoder_Provider_GoogleMapsService.php')) && false ?: '_'}));

return $instance;
