<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.user.form.gender_list' shared service.

return $this->services['sonata.user.form.gender_list'] = new \Sonata\UserBundle\Form\Type\UserGenderListType('Cocorico\\UserBundle\\Entity\\User', 'getGenderList', 'Sonata\\UserBundle\\Form\\Type\\UserGenderListType');
