<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'assetic.filter.minifycsscompressor' shared service.

return $this->services['assetic.filter.minifycsscompressor'] = new \Assetic\Filter\MinifyCssCompressorFilter();
