<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'a2lix_translation_form.default.type.translationsFields' shared service.

return $this->services['a2lix_translation_form.default.type.translationsFields'] = new \A2lix\TranslationFormBundle\Form\Type\TranslationsFieldsType();
