<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico.breadcrumbs_yaml_parser' shared service.

return $this->services['cocorico.breadcrumbs_yaml_parser'] = new \Symfony\Component\Yaml\Parser();
