<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico_time.form.type.date_range' shared service.

return $this->services['cocorico_time.form.type.date_range'] = new \Cocorico\TimeBundle\Form\Type\DateRangeType(1440, 360);
