<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico.form.handler.booking_price' shared service.

return $this->services['cocorico.form.handler.booking_price'] = new \Cocorico\CoreBundle\Form\Handler\Frontend\BookingPriceFormHandler(${($_ = isset($this->services['session']) ? $this->services['session'] : $this->getSessionService()) && false ?: '_'}, ${($_ = isset($this->services['request_stack']) ? $this->services['request_stack'] : $this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()) && false ?: '_'}, ${($_ = isset($this->services['cocorico.listing_search_request']) ? $this->services['cocorico.listing_search_request'] : $this->load(__DIR__.'/getCocorico_ListingSearchRequestService.php')) && false ?: '_'}, ${($_ = isset($this->services['cocorico.booking.manager']) ? $this->services['cocorico.booking.manager'] : $this->load(__DIR__.'/getCocorico_Booking_ManagerService.php')) && false ?: '_'});
