<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico.listing_image_upload_validation_listener' shared service.

return $this->services['cocorico.listing_image_upload_validation_listener'] = new \Cocorico\CoreBundle\Listener\ListingImageUploadValidationListener(12);
