<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico.authentication_success_listener' shared service.

return $this->services['cocorico.authentication_success_listener'] = new \Cocorico\CoreBundle\Authentication\Handler\LoginSuccessHandler(${($_ = isset($this->services['security.http_utils']) ? $this->services['security.http_utils'] : $this->getSecurity_HttpUtilsService()) && false ?: '_'}, array('target_path_parameter' => 'redirect_to', 'login_path' => 'cocorico_user_login', 'use_referer' => true));
