<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico.ajax.authentication_listener' shared service.

return $this->services['cocorico.ajax.authentication_listener'] = new \Cocorico\CoreBundle\Listener\AjaxAuthenticationListener();
