<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico_user.user.validator' shared service.

return $this->services['cocorico_user.user.validator'] = new \Cocorico\UserBundle\Validator\Constraints\UserValidator(6, 1);
