<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico.listing_availability.manager' shared service.

return $this->services['cocorico.listing_availability.manager'] = new \Cocorico\CoreBundle\Model\Manager\ListingAvailabilityManager(${($_ = isset($this->services['doctrine_mongodb.odm.default_document_manager']) ? $this->services['doctrine_mongodb.odm.default_document_manager'] : $this->getDoctrineMongodb_Odm_DefaultDocumentManagerService()) && false ?: '_'}, ${($_ = isset($this->services['cocorico.listing_availability_time.manager']) ? $this->services['cocorico.listing_availability_time.manager'] : $this->load(__DIR__.'/getCocorico_ListingAvailabilityTime_ManagerService.php')) && false ?: '_'}, 1440, 1, true);
