<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico.listing.manager' shared service.

return $this->services['cocorico.listing.manager'] = new \Cocorico\CoreBundle\Model\Manager\ListingManager(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, ${($_ = isset($this->services['security.token_storage']) ? $this->services['security.token_storage'] : $this->services['security.token_storage'] = new \Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage()) && false ?: '_'}, 1, 10, ${($_ = isset($this->services['cocorico.mailer.twig_swift']) ? $this->services['cocorico.mailer.twig_swift'] : $this->load(__DIR__.'/getCocorico_Mailer_TwigSwiftService.php')) && false ?: '_'});
