<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico.form.type.listing_edit_categories_ajax' shared service.

return $this->services['cocorico.form.type.listing_edit_categories_ajax'] = new \Cocorico\CoreBundle\Form\Type\Dashboard\ListingEditCategoriesAjaxType(${($_ = isset($this->services['debug.event_dispatcher']) ? $this->services['debug.event_dispatcher'] : $this->getDebug_EventDispatcherService()) && false ?: '_'});
