<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'cocorico_user.mailer.twig_swift' shared service.

$a = ${($_ = isset($this->services['twig']) ? $this->services['twig'] : $this->getTwigService()) && false ?: '_'};

if (isset($this->services['cocorico_user.mailer.twig_swift'])) {
    return $this->services['cocorico_user.mailer.twig_swift'];
}

return $this->services['cocorico_user.mailer.twig_swift'] = new \Cocorico\UserBundle\Mailer\TwigSwiftMailer(${($_ = isset($this->services['swiftmailer.mailer.default']) ? $this->services['swiftmailer.mailer.default'] : $this->load(__DIR__.'/getSwiftmailer_Mailer_DefaultService.php')) && false ?: '_'}, ${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'}, $a, ${($_ = isset($this->services['request_stack']) ? $this->services['request_stack'] : $this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()) && false ?: '_'}, array('templates' => array('account_created_user' => 'CocoricoUserBundle:Mails/User:account_created_user.txt.twig', 'forgot_password_user' => 'CocoricoUserBundle:Mails/User:forgot_password_user.txt.twig', 'account_creation_confirmation_user' => 'CocoricoUserBundle:Mails/User:account_creation_confirmation_user.txt.twig'), 'from_email' => 'no-reply@cocorico.io', 'site_name' => 'Costocking.com', 'locales' => $this->parameters['cocorico.locales'], 'locale' => 'fr'));
