<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cocorico_user.namer.image_namer' shared service.

return $this->services['cocorico_user.namer.image_namer'] = new \Cocorico\UserBundle\Namer\ImageNamer();
