<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'lexik_currency.oer_adapter' shared service.

$this->services['lexik_currency.oer_adapter'] = $instance = ${($_ = isset($this->services['lexik_currency.adapter_factory']) ? $this->services['lexik_currency.adapter_factory'] : $this->load(__DIR__.'/getLexikCurrency_AdapterFactoryService.php')) && false ?: '_'}->createOerAdapter();

$instance->setOerUrl('http://openexchangerates.org/api/latest.json');
$instance->setOerAppId(NULL);

return $instance;
