<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'lexik_currency.doctrine_adapter' shared service.

return $this->services['lexik_currency.doctrine_adapter'] = ${($_ = isset($this->services['lexik_currency.adapter_factory']) ? $this->services['lexik_currency.adapter_factory'] : $this->load(__DIR__.'/getLexikCurrency_AdapterFactoryService.php')) && false ?: '_'}->createDoctrineAdapter('Cocorico\\CurrencyBundle\\Adapter\\DoctrineCurrencyAdapter', 'default');
