<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.access.listing_image_voter' shared service.

return $this->services['security.access.listing_image_voter'] = new \Cocorico\CoreBundle\Security\Voter\ListingImageVoter();
